version: 2 # use Circle CI 2.0
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/go
    docker: # use docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11.5
    working_directory: /home/circleci/go/src/github.com/sample/pmd2cs
    steps: # checkout + alpha
      - checkout
      - run: echo "Hello Circle CI. Hello world."
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      - run: echo "Circle CI. success go test."
